name: CI Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: set -o pipefail && curl --fail --location https://raw.githubusercontent.com/coolbho3k/Build-Automation_MiSTer/kernel_test/build.sh | bash -
      env:
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISPATCH_TOKEN: ${{ secrets.BUILD_AUTOMATION_DISPATCH_TOKEN }}
